"""
pybind11 bindings for libpst: read Microsoft Outlook .pst files
"""
from __future__ import annotations
import typing
__all__: list[str] = ['Appointment', 'Attachment', 'Contact', 'Folder', 'Journal', 'Message', 'PstFile', 'open']
class Appointment:
    def __repr__(self) -> str:
        ...
    @property
    def all_day(self) -> bool:
        ...
    @property
    def body(self) -> str:
        ...
    @property
    def busy_status(self) -> int:
        ...
    @property
    def end(self) -> str:
        ...
    @property
    def is_recurring(self) -> bool:
        ...
    @property
    def location(self) -> str:
        ...
    @property
    def recurrence_description(self) -> str:
        ...
    @property
    def recurrence_type(self) -> int:
        ...
    @property
    def start(self) -> str:
        ...
    @property
    def subject(self) -> str:
        ...
    @property
    def timezone(self) -> str:
        ...
class Attachment:
    def __repr__(self) -> str:
        ...
    @property
    def content_id(self) -> str:
        ...
    @property
    def data(self) -> bytes:
        """
        Raw attachment bytes (may be empty for reference-only attachments).
        """
    @property
    def filename(self) -> str:
        ...
    @property
    def method(self) -> int:
        ...
    @property
    def mimetype(self) -> str:
        ...
    @property
    def position(self) -> int:
        ...
    @property
    def size(self) -> int:
        ...
class Contact:
    def __repr__(self) -> str:
        ...
    @property
    def business_address(self) -> str:
        ...
    @property
    def business_phone(self) -> str:
        ...
    @property
    def company_name(self) -> str:
        ...
    @property
    def department(self) -> str:
        ...
    @property
    def display_name(self) -> str:
        ...
    @property
    def email1(self) -> str:
        ...
    @property
    def email2(self) -> str:
        ...
    @property
    def email3(self) -> str:
        ...
    @property
    def first_name(self) -> str:
        ...
    @property
    def fullname(self) -> str:
        ...
    @property
    def home_address(self) -> str:
        ...
    @property
    def home_phone(self) -> str:
        ...
    @property
    def job_title(self) -> str:
        ...
    @property
    def mobile_phone(self) -> str:
        ...
    @property
    def nickname(self) -> str:
        ...
    @property
    def surname(self) -> str:
        ...
class Folder:
    def __repr__(self) -> str:
        ...
    @property
    def appointments(self) -> list[Appointment]:
        ...
    @property
    def contacts(self) -> list[Contact]:
        ...
    @property
    def journals(self) -> list[Journal]:
        ...
    @property
    def messages(self) -> list[Message]:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def subfolders(self) -> list[Folder]:
        ...
class Journal:
    def __repr__(self) -> str:
        ...
    @property
    def description(self) -> str:
        ...
    @property
    def end(self) -> str:
        ...
    @property
    def start(self) -> str:
        ...
    @property
    def subject(self) -> str:
        ...
    @property
    def type(self) -> str:
        ...
class Message:
    def __repr__(self) -> str:
        ...
    @property
    def attachment_names(self) -> list[str]:
        ...
    @property
    def attachments(self) -> list[Attachment]:
        ...
    @property
    def bcc(self) -> str:
        ...
    @property
    def cc(self) -> str:
        ...
    @property
    def comment(self) -> str:
        ...
    @property
    def date(self) -> str:
        ...
    @property
    def header(self) -> str:
        ...
    @property
    def html(self) -> str:
        ...
    @property
    def importance(self) -> int:
        ...
    @property
    def in_reply_to(self) -> str:
        ...
    @property
    def message_id(self) -> str:
        ...
    @property
    def plain_text(self) -> str:
        ...
    @property
    def priority(self) -> int:
        ...
    @property
    def reply_to(self) -> str:
        ...
    @property
    def rtf(self) -> str:
        ...
    @property
    def sender(self) -> str:
        ...
    @property
    def sender_name(self) -> str:
        ...
    @property
    def sensitivity(self) -> int:
        ...
    @property
    def sent_date(self) -> str:
        ...
    @property
    def subject(self) -> str:
        ...
    @property
    def to(self) -> str:
        ...
class PstFile:
    def __enter__(self) -> PstFile:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> bool:
        ...
    def __init__(self, path: str, charset: str = 'UTF-8') -> None:
        ...
    def close(self) -> None:
        ...
    @property
    def root(self) -> Folder:
        ...
def open(path: str, charset: str = 'UTF-8') -> PstFile:
    """
    Open a .pst file and return a PstFile whose .root is the folder tree.
    """
__version__: str = '0.1.0'
